CFLAGS=-lm -fopenmp -Wall

all: matrices-original matrices-filas matrices-columnas

matrices-original:
matrices-filas:
matrices-columnas:

clean:
	rm matrices-columnas matrices-filas matrices-original


